package com.example.meituan.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.meituan.beans.BusinessInformation;
import com.example.meituan.beans.DishInfo;
import com.example.meituan.beans.UserInfo;

import com.example.meituan.db.BusinessInformationDao;
import com.example.meituan.db.DishInfoDao;
import com.example.meituan.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig businessInformationDaoConfig;
    private final DaoConfig dishInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final BusinessInformationDao businessInformationDao;
    private final DishInfoDao dishInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        businessInformationDaoConfig = daoConfigMap.get(BusinessInformationDao.class).clone();
        businessInformationDaoConfig.initIdentityScope(type);

        dishInfoDaoConfig = daoConfigMap.get(DishInfoDao.class).clone();
        dishInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        businessInformationDao = new BusinessInformationDao(businessInformationDaoConfig, this);
        dishInfoDao = new DishInfoDao(dishInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(BusinessInformation.class, businessInformationDao);
        registerDao(DishInfo.class, dishInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        businessInformationDaoConfig.clearIdentityScope();
        dishInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public BusinessInformationDao getBusinessInformationDao() {
        return businessInformationDao;
    }

    public DishInfoDao getDishInfoDao() {
        return dishInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
